### ISSUE TITLE
Templates are not created using `raco new`

### ISSUE THREAD

**Issue by countvajhula** [racket-templates/racket-templates#4]
I tried these commands in the shell:
```
raco new qi-tutorial
raco new template
raco new rosette
raco new rosette rosette-project
raco new --list
```

None of them had any effect. I tried `raco pkg update from-template` and it says "No updates available"

Any ideas? I'm on Racket 8.3.

**Comment by nixin72** [comment]
Ahh, so sorry about that, the newest version of the tool isn't pushed to the package archive :facepalm: I'll do that now.

**Comment by nixin72** [comment]
Ahh, so sorry about that @countvajhula, it's from my misunderstanding of how modules work from the looks of it. Thanks for bringing this to my attention, I'll get it fixed asap!

**Comment by countvajhula** [comment]
No worries @nixin72 , thanks for your efforts!

**Comment by nixin72** [comment]
Okay, this has been fixed @countvajhula! So sorry for the inconvenience!

**Comment by countvajhula** [comment]
I see the templates now with `raco new --list`, and am able to instantiate them as well 👍
